#!/bin/bash

if [ -n "$DEBUG" ]; then
  if [ ! -d .venv-dev ]; then
    python -m venv .venv-dev
  fi
  source .venv-dev/bin/activate
else
  if [ ! -d .venv-prod ]; then
    python -m venv .venv-prod
  fi
  source .venv-prod/bin/activate
fi

if ! [ -x "$(command -v pip-sync)" ]; then
  pip install pip-tools==1.8.2
fi

if [ -n "$DEBUG" ]; then
  pip-sync requirements_dev.txt
else
  pip-sync requirements.txt
fi

exec "$@"
