---
# .about.yml project metadata

# This is a short name of your project that can be used as a URL slug.
# (required)
name: atf-eregs

# This is the display name of your project. (required)
full_name: ATF eRegulations

# What is the problem your project solves? What is the solution? (required)
description: The Bureau of Alcohol, Tobacco, Firearms and Explosives (ATF) maintains a large amount of complex information that the public needs to use, including regulations with important requirements related to munitions, firearms, and explosives. 18F adapted and customized eRegulations, an open source project started by the Consumer Financial Protection Bureau in 2013, to make ATF's regulations easier to find, read, and understand.

# What is the measurable impact of your project? (required)
impact: We produced a web application that offers substantial support for reading complex legal information, which helps ATF serve the public.

# What kind of team owns the repository? (required)
# values: guild, working-group, project
owner_type: project

# What is your project's current status? (required)
# values: discovery, alpha, beta, live
stage: live

# Should this repo have automated tests? If so, set to `true`. (required)
# values: true, false
testable: true

# What are the licenses that apply to the project and/or its components?
# (required)
# Items by property name pattern:
#   .*:
#     name: Name of the license from the Software Package Data Exchange (SPDX): https://spdx.org/licenses/
#     url: URL for the text of the license
licenses:
  atf-eregs:
    name: CC0-1.0
    url: https://github.com/18F/atf-eregs/blob/master/LICENSE.md

# Who is the partner for your project? (Use the full name of the partner
# documented here:
# https://github.com/18F/dashboard/blob/staging/_data/partners.yml)
partners:
- Bureau of Alcohol, Tobacco, Firearms and Explosives

# The main point of contact(s) and/or the issue reporting system for your
# project, and either a `mailto:` link or URL for each contact.
# Items:
# - url: URL for the link
#   text: Anchor text for the link
contact:
- url: https://github.com/18F/atf-eregs/issues
  text: GitHub issues

# Who are the team members on your project? You can specify GitHub usernames,
# email addresses, or other organizational usernames. (required)
# Items:
# - github: GitHub user name
#   id: Internal team identifier/user name
#   role: Team member's role; leads should be designated as 'lead'
team:
- github: brittag
  role: Content Designer
- github: cmc333333
  role: Engineer
- github: jbarnicle
  role: Engineer
- github: jehlers
  role: User Experience Designer
- github: journerdism
  role: Product Manager
- github: tadhg-ohiggins
  role: Engineer
- github: theresaanna
  role: Engineer
- github: vrajmohan
  role: Engineer

# What kind of content is contained in the project repository?
# values: app, docs, policy
type: app

# What are the key milestones you've achieved recently?
#milestones:
#- 

# Name of the main project repo if this is a sub-repo; name of the grouplet
# repo if this is a working group/guild subproject
#parent:

# What are the links to key artifacts associated with your project? e.g. the
# production site, documentation.
# Items:
# - url: URL for the link
#   text: Anchor text for the link
#   category: Type of the link
links:
- url: https://atf-eregs.apps.cloud.gov/
  text: ATF eRegulations website

# What tags does your organization's blog associate with your project? You can
# find a list of 18F blog tags here: https://18f.gsa.gov/tags/
#blogTag:
#- 

# What technologies are used in this project?
#stack:
#- 

# What are the services used to supply project status information?
# Items:
# - name: Name of the service
#   category: Type of the service
#   url: URL for detailed information
#   badge: URL for the status badge
#services:
#- 

# Organizations or individuals who have adopted the project for their own use
# Items:
# - id: The name of the organization or individual
#   url: A URL to the user's version of the project
#users:
#- 

# Tags that describe the project or aspects of the project
#tags:
#- 