language: python
sudo: false
python: 3.5
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
install:
  - pip install -r requirements_dev.txt
  - npm install
script:
  - py.test
  - flake8
  - webpack
