language: python
sudo: false
python: 3.5
before_install:
  - nvm install node
install:
  - pip install -r requirements_dev.txt
  - npm install
  - export PKG=eslint-config-airbnb; npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install --save-dev "$PKG@latest"
script:
  - py.test
  - flake8
  - webpack
