language: generic
sudo: required
services:
- docker
script:
- docker-compose run --rm npm install --quiet
- docker-compose run --rm npm test
- docker-compose run --rm webpack
- docker-compose run --rm py.test
- docker-compose run --rm flake8
- docker-compose run --rm manage.py migrate --noinput
- docker-compose run --rm manage.py fetch_csv
- docker-compose run --rm manage.py import_reqs data.csv
before_deploy:
- export PATH=$HOME:$PATH
- travis_retry curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github"
  | tar -zx
- travis_retry wget "https://github.com/contraband/autopilot/releases/download/0.0.3/autopilot-linux"
- chmod a+x autopilot-linux
- mv cf $HOME
- mv autopilot-linux $HOME
- cf install-plugin -f ~/autopilot-linux
deploy:
  provider: script
  script: devops/deploy.sh dev
  skip_cleanup: true
  on:
    branch: master
after_success:
  - docker-compose run --rm dev npm install codeclimate-test-reporter
  - docker-compose run --rm dev ./node_modules/.bin/codeclimate-test-reporter < ui/lcov.info
