language: generic
sudo: required
services:
- docker
before_install:
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
- docker --version
script:
# JS tests
- docker-compose run --rm npm test
# Smoke test and lint
- docker-compose run --rm webpack
# Python tests and linting
- docker-compose run --rm py.test
- docker-compose run --rm flake8
# Integration tests
- ./devops/integration-tests.sh
before_deploy:
- export PATH=$HOME:$PATH
- travis_retry curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github"
  | tar -zx
- travis_retry wget "https://github.com/contraband/autopilot/releases/download/0.0.3/autopilot-linux"
- chmod a+x autopilot-linux
- mv cf $HOME
- mv autopilot-linux $HOME
- cf install-plugin -f ~/autopilot-linux
deploy:
  provider: script
  script: devops/deploy.sh dev
  skip_cleanup: true
  on:
    branch: master
after_success:
- docker-compose run --rm dev npm install codeclimate-test-reporter
- docker-compose run --rm -e CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN dev ./node_modules/.bin/codeclimate-test-reporter < ui/lcov.info
