language: generic
sudo: required
services:
- docker
script:
# JS tests
- docker-compose run --rm npm test
# Smoke test and lint
- docker-compose run --rm webpack
# Python tests and linting
- docker-compose run --rm py.test
- docker-compose run --rm flake8
- docker-compose run --rm bandit -r ereqs_admin reqs omb_eregs -s B101  # skip asserts
# Integration tests
# - ./devops/integration-tests.sh
before_deploy:
- export PATH=$HOME:$PATH
- travis_retry curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github"
  | tar -zx
- travis_retry wget "https://github.com/contraband/autopilot/releases/download/0.0.3/autopilot-linux"
- chmod a+x autopilot-linux
- mv cf $HOME
- mv autopilot-linux $HOME
- cf install-plugin -f ~/autopilot-linux
deploy:
  - provider: script
    script: devops/deploy.sh prod
    skip_cleanup: true
    on:
      branch: release
