version: '2.1'
services:
  persistent_db:
    image: postgres:9.4
    volumes:
      - database_data:/var/lib/postgresql/data
  minio:
    extends:
      file: docker-services.yml
      service: minio
  api:
    extends:
      file: docker-services.yml
      service: dev-api
    volumes:
      - .:/usr/src/app:delegated
    depends_on:
      - persistent_db
      - minio
      - api-ui
  api-ui:
    extends:
      file: docker-services.yml
      service: api-webpack
    volumes:
      - .:/usr/src/app:delegated
  ui:
    extends:
      file: docker-services.yml
      service: dev
    volumes:
      - .:/usr/src/app:delegated
    depends_on:
      - api
volumes:
  database_data:
