version: '2.1'
services:
  persistent_db:
    image: postgres:9.4
    volumes:
      - database_data:/var/lib/postgresql/data
  minio:
    extends:
      file: docker-services.yml
      service: minio
  dev-api:
    extends:
      file: docker-services.yml
      service: dev-api
    volumes:
      - .:/usr/src/app:delegated
    depends_on:
      - persistent_db
      - minio
      - api-webpack
  api-webpack:
    extends:
      file: docker-services.yml
      service: api-webpack
    volumes:
      - .:/usr/src/app:delegated
  dev:
    extends:
      file: docker-services.yml
      service: dev
    volumes:
      - .:/usr/src/app:delegated
    depends_on:
      - dev-api
volumes:
  database_data:
