version: '2.1'
services:
  persistent_db:
    extends:
      file: docker-services.yml
      service: persistent_db
  minio:
    extends:
      file: docker-services.yml
      service: minio
  dev-api:
    extends:
      file: docker-services.yml
      service: dev-api
    depends_on:
      - persistent_db
      - minio
      - api-webpack-watcher
  api-webpack-watcher:
    extends:
      file: docker-services.yml
      service: api-webpack-watcher
  dev:
    extends:
      file: docker-services.yml
      service: dev
    depends_on:
      - dev-api
volumes:
  database_data:
