version: '2'
services:
  # This service is a shared network stack (i.e. shared "localhost") for all
  # external-facing services. It allows "localhost" links to work correctly
  # outside of Docker.
  proxy:
    image: busybox
    command: sleep 100d   # do nothing
    ports:  # forwarded
      - 8001:8001   # dev-api
      - 8002:8002   # dev
      - 9001:9001   # prod-api
      - 9002:9002   # prod
      - 9100:9100   # minio

  persistent_db:
    image: postgres:9.4
    volumes:
      - database_data:/var/lib/postgresql/data
  python: &PYTHON     # This command is out of order to aid with config reuse
    image: python:3.6.2
    volumes:
      - $PWD:/usr/src/app
    working_dir: /usr/src/app
    stdin_open: true
    tty: true
  minio:
    image: minio/minio
    environment:
        - MINIO_ACCESS_KEY=LOCAL_ID
        - MINIO_SECRET_KEY=LOCAL_KEY
    command: server --address ':9100' minio-test
    network_mode: service:proxy
  prod-api: &PROD_API
    <<: *PYTHON
    command: ./devops/wait_for_db_then ./devops/activate_then ./devops/run_api.sh
    environment: &API_ENV
      DATABASE_URL: postgres://postgres@persistent_db/postgres
      PORT: 9001
      DJANGO_SETTINGS_MODULE: omb_eregs.settings
      TMPDIR: /tmp
      USING_SSL: "False"
      # Uncomment the following line for MAX logins
      # MAX_URL: https://login.max.gov/cas/login
      # The following settings are to maintain environment parity between the
      # docker-compose configuration for local development and the cloud.gov
      # staging and production configurations.
      VCAP_APPLICATION: >
        {"uris": ["localhost", "0.0.0.0", "127.0.0.1", "prod-api", "dev-api", "proxy"]}
      VCAP_SERVICES: >
        {"config": [{"credentials": {"DJANGO_SECRET_KEY": "NotASecret"}}],
         "s3": [{
           "credentials": {
             "access_key_id": "LOCAL_ID",
             "bucket": "pdfs",
             "region": "irrelevant fake region",
             "endpoint": "http://0.0.0.0:9100",
             "secret_access_key": "LOCAL_KEY"
           },
           "label": "s3",
           "name": "storage-s3"
         }]
        }
    depends_on:
      - persistent_db
      - minio
    network_mode: service:proxy

  dev-api: &DEV_API
    <<: *PROD_API
    command: ./devops/wait_for_db_then ./devops/activate_then ./devops/run_api.sh
    environment:
      <<: *API_ENV
      PORT: 8001
      DEBUG: "true"
      # Uncomment the following line for MAX logins
      # MAX_URL: https://login.test.max.gov/cas/login

  prod: &PROD_UI
    image: node:6
    volumes:
      - $PWD:/usr/src/app
    working_dir: /usr/src/app
    command: ./devops/deps_ok_then npm start
    environment: &UI_ENV
      PORT: 9002
      NODE_ENV: production
      API_URL: 'http://0.0.0.0:9001/'
      VCAP_SERVICES: >
        {"config": [{"name": "config", "credentials": {"UI_BASIC_AUTH": {
        }}}]}
    depends_on:
      - prod-api
    network_mode: service:proxy

  dev: &DEV_UI
    <<: *PROD_UI
    command: ./devops/deps_ok_then ./devops/dev_ui.sh
    environment:
      <<: *UI_ENV
      PORT: 8002
      NODE_ENV: ''
      API_URL: 'http://0.0.0.0:8001/'
      VCAP_SERVICES: >
        {"config": [{"name": "config", "credentials": {"UI_BASIC_AUTH": {
        }}}]}
    depends_on:
      - dev-api


  #---- Commands ----
  flake8:
    <<: *PYTHON
    environment:
      DEBUG: "true"
    entrypoint: ./devops/activate_then flake8

  pip-compile:
    <<: *PYTHON
    environment:
      DEBUG: "true"
    entrypoint: ./devops/activate_then pip-compile

  bandit:
    <<: *PYTHON
    environment:
      DEBUG: "true"
    entrypoint: ./devops/activate_then bandit


  manage.py:
    <<: *DEV_API
    entrypoint: ./devops/wait_for_db_then ./devops/activate_then ./manage.py
    command: ''

  py.test:
    <<: *DEV_API
    entrypoint: ./devops/wait_for_db_then ./devops/activate_then py.test
    command: ''

  npm:
    <<: *DEV_UI
    entrypoint: ./devops/deps_ok_then npm
    command: ''
    ports: []
    depends_on: []

  webpack:
    <<: *DEV_UI
    entrypoint: ./devops/deps_ok_then ./node_modules/.bin/webpack
    command: ''
    ports: []
    depends_on: []

  psql:
    image: postgres:9.4
    entrypoint: 'psql -h persistent_db -U postgres'
    depends_on: ['persistent_db']

volumes:
  database_data:
