version: '2.1'
services:
  persistent_db:
    image: postgres:9.4
    volumes:
      - database_data:/var/lib/postgresql/data
  api:
    image: python:3.6.4
    working_dir: /usr/src/app/api
    stdin_open: true
    tty: true
    entrypoint: .docker/activate_then .docker/wait_for_webpack_then .docker/wait_for_db_then
    command: ./run_api.sh
    environment:
      PORT: 8001
      DEBUG: ${DEBUG:-true}
      USE_POLLING: ${USE_POLLING:-false}
      DATABASE_URL: postgres://postgres@persistent_db/postgres
      DJANGO_SETTINGS_MODULE: omb_eregs.settings
      TMPDIR: /tmp
      USING_SSL: "False"

      # The following settings are to maintain environment parity between the
      # docker-compose configuration for local development and the cloud.gov
      # staging and production configurations.
      VCAP_APPLICATION: >
        {"uris": ["localhost", "0.0.0.0", "127.0.0.1", "api"]}
      VCAP_SERVICES: >
        {"config": [{"credentials": {"DJANGO_SECRET_KEY": "NotASecret"}}]}
    ports:
      - 8001:8001
    volumes:
      - .:/usr/src/app:delegated
    depends_on:
      - persistent_db
      - api-ui
  api-ui:
    image: node:8
    environment:
      USE_POLLING: ${USE_POLLING:-false}
    working_dir: /usr/src/app/api
    entrypoint: .docker/deps_ok_then .docker/modify_path_then
    command: webpack --watch
    volumes:
      - .:/usr/src/app:delegated
  ui:
    image: node:8
    working_dir: /usr/src/app/ui
    entrypoint: .docker/deps_ok_then .docker/modify_path_then
    command: .docker/watch-run.sh
    environment:
      PORT: 8002
      NODE_ENV: ${NODE_ENV:-development}
      API_URL: ${API_URL:-http://localhost:8001/}
      INTERNAL_API_URL: ${INTERNAL_API_URL:-http://api:8001/}
      USE_POLLING: ${USE_POLLING:-false}
      VCAP_SERVICES: >
        {"config": [{"name": "config", "credentials": {"UI_BASIC_AUTH": {
        }}}]}
    ports:
      - 8002:8002
    volumes:
      - .:/usr/src/app:delegated
    depends_on:
      - api
  styleguide:
    image: node:8
    working_dir: /usr/src/app/styleguide
    entrypoint: .docker/deps_ok_then .docker/modify_path_then
    command: .docker/build_run_styleguide
    environment:
      USE_POLLING: ${USE_POLLING:-false}
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app:delegated
volumes:
  database_data:
