version: '2'
services:
  persistent_db:
    image: postgres:9.4
    volumes:
      - database_data:/var/lib/postgresql/data

  prod-api: &PROD_API
    image: omb-eregs:prod
    build:
      context: .
    command: ./devops/wait_for_db_then ./devops/prod_api.sh
    ports:
      - "8001:8001"
    environment: &API_ENV
      DATABASE_URL: postgres://postgres@persistent_db/postgres
      PORT: 8001
      DJANGO_SETTINGS_MODULE: omb_eregs.settings
      TMPDIR: /tmp
      # Uncomment the following line for MAX logins
      # MAX_URL: https://login.max.gov/cas/login
      VCAP_APPLICATION: >
        {"uris": ["localhost", "0.0.0.0", "127.0.0.1", "prod-api", "dev-api"]}
      VCAP_SERVICES: >
        {"config": [{"credentials": {"DJANGO_SECRET_KEY": "NotASecret"}}]}
    volumes:
      - $PWD:/code    # override to source the current directory
    depends_on:
      - persistent_db
    stdin_open: true
    tty: true

  dev-api: &DEV_API
    <<: *PROD_API
    image: omb-eregs:debug
    build:
      context: .
      args:
        DEV_MODE: "true"
    command: ./devops/wait_for_db_then ./devops/dev_api.sh
    environment:
      <<: *API_ENV
      DEBUG: "true"
      # Uncomment the following line for MAX logins
      # MAX_URL: https://login.test.max.gov/cas/login

  prod: &PROD_UI
    image: node:6
    volumes:
      - $PWD:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    ports:
      - "8000:8000"
    environment: &UI_ENV
      PORT: 8000
      NODE_ENV: production
      INTERNAL_API: 'http://prod-api:8001/'
      PUBLIC_API: 'http://0.0.0.0:8001/'
      VCAP_SERVICES: >
        {"config": [{"name": "config", "credentials": {"UI_BASIC_AUTH": {
        }}}]}
    depends_on:
      - prod-api

  dev: &DEV_UI
    <<: *PROD_UI
    command: ./devops/dev_ui.sh
    environment:
      <<: *UI_ENV
      NODE_ENV: ''
      INTERNAL_API: 'http://dev-api:8001/'
      PUBLIC_API: 'http://0.0.0.0:8001/'
      VCAP_SERVICES: >
        {"config": [{"name": "config", "credentials": {"UI_BASIC_AUTH": {
        }}}]}
    depends_on:
      - dev-api


  #---- Commands ----
  manage.py:
    <<: *PROD_API
    entrypoint: ./devops/wait_for_db_then ./manage.py
    command: ''
    ports: []

  py.test:
    <<: *DEV_API
    entrypoint: ./devops/wait_for_db_then py.test
    command: ''
    ports: []

  flake8:
    <<: *DEV_API
    entrypoint: flake8
    depends_on: []
    command: ''
    ports: []

  pip-compile:
    <<: *DEV_API
    entrypoint: pip-compile
    depends_on: []
    command: ''
    ports: []

  npm:
    <<: *DEV_UI
    entrypoint: npm
    command: ''
    ports: []

  webpack:
    <<: *DEV_UI
    entrypoint: ./node_modules/.bin/webpack
    command: ''
    ports: []

  psql:
    image: postgres:9.4
    entrypoint: 'psql -h persistent_db -U postgres'
    depends_on: ['persistent_db']

volumes:
  database_data:
