# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 19:17
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    Requirement = apps.get_model('reqs', 'Requirement')
    Requirement.objects.filter(omb_policy_id='NA').update(omb_policy_id='')
    Requirement.objects.filter(omb_policy_id='None').update(omb_policy_id='')


class Migration(migrations.Migration):
    dependencies = [('reqs', '0002_auto_20170125_1917') ]
    operations = [migrations.RunPython(forward)]
