# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0003_auto_20170125_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='policy_type',
            field=models.CharField(choices=[('memorandum', 'Memorandum'), ('circular', 'Circular'), ('strategy', 'Strategy'), ('review', 'Policy Review')], max_length=32),
        ),
    ]
