# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0007_auto_20170127_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='policy_issuance_year',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='policy_subset',
        ),
    ]
