# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0015_auto_20170214_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'verbose_name': 'Keyword', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['policy_number'], 'verbose_name_plural': 'Policies'},
        ),
        migrations.AlterModelOptions(
            name='requirement',
            options={'ordering': ['req_id']},
        ),
        migrations.AlterField(
            model_name='requirement',
            name='keywords',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='reqs.KeywordConnect', to='reqs.Keyword', verbose_name='Topics'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='req_id',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
