# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0018_auto_20170307_1554'),
        ('reqs', '0018_auto_20170228_1727'),
    ]

    operations = [
    ]
