# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0019_merge_20170307_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(blank=True, choices=[('circular', 'Circular'), ('executive', 'Executive Order'), ('guidance', 'Guidance'), ('hspd', 'HSPD'), ('law', 'Law'), ('memorandum', 'Memorandum'), ('national_action', 'National Action Plan'), ('plan', 'Plan'), ('ppd', 'PPD'), ('review', 'Policy Review'), ('standards', 'Standards'), ('strategy', 'Strategy')], max_length=32),
        ),
    ]
