# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0022_auto_20170329_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='keywords',
        ),
        migrations.RenameModel(
            old_name='KeywordConnect',
            new_name='TopicConnect',
        ),
        migrations.RenameModel(
            old_name='Keyword',
            new_name='Topic',
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AddField(
            model_name='requirement',
            name='topics',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='reqs.TopicConnect', to='reqs.Topic', verbose_name='Topics'),
        ),
        migrations.AlterField(
            model_name='topicconnect',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='reqs.Topic'),
        ),
    ]
