# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0023_auto_20170418_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='reqs.Policy'),
        ),
    ]
