# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0025_policy_document_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='nonpublic',
            field=models.NullBooleanField(),
        ),
    ]
