# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0027_auto_20170511_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='agencies',
            field=models.ManyToManyField(to='reqs.Agency'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='agency_groups',
            field=models.ManyToManyField(to='reqs.AgencyGroup'),
        ),
    ]
