# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0032_auto_20170601_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='issuing_body',
        ),
    ]
