# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0031_auto_20170531_1242'),
        ('reqs', '0033_auto_20170601_1753'),
    ]

    operations = [
    ]
