# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0036_auto_20170606_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.RunSQL(
            "UPDATE reqs_agency SET public = NOT nonpublic",
            "UPDATE reqs_agency SET nonpublic = NOT public"
        ),
        migrations.RunSQL(
            "UPDATE reqs_policy SET public = NOT nonpublic",
            "UPDATE reqs_policy SET nonpublic = NOT public"
        ),
        migrations.RemoveField(
            model_name='agency',
            name='nonpublic',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='nonpublic',
        ),
    ]
