# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0036_auto_20170606_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='slug',
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
