# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0037_auto_20170613_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
