# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0037_auto_20170613_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='requirements', to='reqs.Topic'),
        ),
        migrations.RunSQL(
            """
                INSERT INTO reqs_requirement_topics (requirement_id, topic_id)
                (SELECT content_object_id, tag_id
                 FROM reqs_topicconnect
                 GROUP BY content_object_id, tag_id) --- ensure uniqueness
            """, """
                INSERT INTO reqs_topicconnect (content_object_id, tag_id)
                (SELECT requirement_id, topic_id
                 FROM reqs_requirement_topics)
            """
        ),
        migrations.RemoveField(
            model_name='topicconnect',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='topicconnect',
            name='tag',
        ),
        migrations.DeleteModel(
            name='TopicConnect',
        ),
    ]
