# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0038_requirement_public'),
        ('reqs', '0038_auto_20170613_1816'),
    ]

    operations = [
    ]
