#!/bin/bash

FIRST_RUN=true

until (ls webpack-static 2> /dev/null)
do
  echo "Startup: Waiting for webpack..."
  if $FIRST_RUN; then
    echo "\tTo track progress, run:"
    echo "\tdocker-compose logs -f api-webpack-watcher"
    FIRST_RUN=false
  fi
  sleep 10
done

exec "$@"

