#!/bin/bash

export DEPS_OK=./node_modules/deps-ok/bin/deps-ok.js

if [ ! -x $DEPS_OK ]; then
  echo "Installing deps-ok"
  npm install --save-dev deps-ok
fi

$DEPS_OK &> /dev/null
if [ $? -ne 0 ]; then
  echo "Installing Node dependencies"
  npm install
fi

exec "$@"
