# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 16:26
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    Theme = apps.get_model('admin_interface', 'Theme')
    Theme.objects.create(
        name="USWDS",
        active=True,
        title="OMB Policy Library Editor",
        title_color="#FFFFFF",
        title_visible=True,
        logo="",
        logo_color="#FFFFFF",
        logo_visible=False,
        css_header_background_color="#112E51",
        css_header_text_color="#FFFFFF",
        css_header_link_color="#FFFFFF",
        css_header_link_hover_color="#E1F3F8",
        css_module_background_color="#205493",
        css_module_text_color="#FFFFFF",
        css_module_link_color="#FFFFFF",
        css_module_link_hover_color="#E1F3F8",
        css_module_rounded_corners=True,
        css_generic_link_color="#205493",
        css_generic_link_hover_color="#0071BC",
        css_save_button_background_color="#205493",
        css_save_button_background_hover_color="#112E51",
        css_save_button_text_color="#FFFFFF",
        css_delete_button_background_color="#CD2026",
        css_delete_button_background_hover_color="#981B1E",
        css_delete_button_text_color="#FFFFFF",
        css="",
        related_modal_active=True,
        related_modal_background_color="#000000",
        related_modal_background_opacity=0.8,
        related_modal_rounded_corners=True,
        list_filter_dropdown=False,
        recent_actions_visible=True
    )


def backwards(apps, schema_editor):
    Theme = apps.get_model('admin_interface', 'Theme')
    Theme.objects.filter(name="USWDS").delete()


class Migration(migrations.Migration):
    dependencies = [('admin_interface', '0005_add_recent_actions_visible')]
    operations = [migrations.RunPython(forward, backwards)]
