# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    """Data migration for converting a single-select to a multi-select."""

    dependencies = [
        ('reqs', '0002_policy_managing_offices'),
    ]

    operations = [
        migrations.RunSQL(
            """ INSERT INTO reqs_policy_managing_offices (policy_id, office_id)
                SELECT id, managing_office_id
                FROM reqs_policy
                WHERE managing_office_id IS NOT NULL
            """,
            """ UPDATE reqs_policy SET managing_office_id = (
                    SELECT max(office_id) FROM reqs_policy_managing_offices
                    WHERE policy_id=reqs_policy.id
                );
                DELETE FROM reqs_policy_managing_offices;
            """
        ),
    ]
