# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 20:43
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    Requirement = apps.get_model('reqs', 'Requirement')
    Requirement.objects.filter(policy_type__icontains='memo').update(
        policy_type='Memorandum')


class Migration(migrations.Migration):
    dependencies = [('reqs', '0004_auto_20170125_2041')]
    operations = [migrations.RunPython(forward)]
