# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 00:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0005_auto_20170125_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='policy_issuance',
            field=models.DateField(default=datetime.date(2001, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requirement',
            name='policy_sunset',
            field=models.DateField(blank=True, null=True),
        ),
    ]
