# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0005_requirement_docnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='slug',
            field=models.SlugField(blank=True, max_length=1024),
        ),
    ]
