# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 16:58
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify


def populate_slug(apps, schema_editor):
    # We can't import the Policy model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Policy = apps.get_model('reqs', 'Policy')
    for policy in Policy.objects.filter(slug=''):
        policy.slug = slugify(policy.title)
        policy.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0006_policy_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slug),
    ]
