# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0008_no_blank_slugs_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='docnode',
        ),
    ]
