# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-17 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('reqs', '0010_policy_workflow_phase'), ('reqs', '0011_auto_20180117_1846')]

    dependencies = [
        ('reqs', '0009_remove_requirement_docnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='workflow_phase',
            field=models.CharField(blank=True, choices=[('edit', 'Edit'), ('cleanup', 'Cleanup'), ('failed', 'Failed Import'), ('no_doc', 'No Document'), ('published', 'Published'), ('review', 'Review')], max_length=32),
        ),
    ]
