# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-17 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0010_policy_workflow_phase_squashed_0011_auto_20180117_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='workflow_phase',
            field=models.CharField(choices=[('edit', 'Edit'), ('cleanup', 'Cleanup'), ('failed', 'Failed Import'), ('no_doc', 'No Document'), ('published', 'Published'), ('review', 'Review')], default='no_doc', max_length=32),
        ),
    ]
