# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0010_auto_20170127_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='omb_policy_id',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='policy_issuance',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='policy_number',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='policy_sunset',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='policy_title',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='policy_type',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='uri_policy_id',
        ),
    ]
