# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0011_auto_20170127_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'verbose_name': 'Keyword',
            },
        ),
        migrations.CreateModel(
            name='KeywordConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reqs.Requirement')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword', to='reqs.Keyword')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='requirement',
            name='keywords',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='reqs.KeywordConnect', to='reqs.Keyword', verbose_name='Keywords'),
        ),
    ]
