# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0012_auto_20180118_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['policy_number', 'pk'], 'verbose_name_plural': 'Policies'},
        ),
        migrations.AlterField(
            model_name='policy',
            name='issuing_body',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='uri',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
