# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0013_auto_20170131_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='aquisition',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='cloud',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='customer_services',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='cybersecurity',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='data_centers',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='data_management',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='definitions',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='digital_services',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='financial_systems',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='governance',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='governance_implementation',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='governance_org_structure',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='hardware',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='human_capital',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='it_project_management',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='other_keywords',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='privacy',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='reporting',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='shared_services',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='software',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='statistics',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='transparency',
        ),
    ]
