# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0013_auto_20180125_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='omb_policy_id',
            field=models.CharField(blank=True, help_text='E.g. M-16-19', max_length=64, verbose_name='Policy number'),
        ),
    ]
