# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0017_auto_20170222_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['name'], 'verbose_name': 'Keyword', 'verbose_name_plural': 'Keywords'},
        ),
    ]
