# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0017_auto_20170222_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='omb_policy_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(blank=True, choices=[('memorandum', 'Memorandum'), ('circular', 'Circular'), ('strategy', 'Strategy'), ('review', 'Policy Review'), ('executive', 'Executive Order'), ('guidance', 'Guidance'), ('standards', 'Standards'), ('law', 'Law'), ('plan', 'Plan'), ('hspd', 'HSPD'), ('ppd', 'PPD'), ('national_action', 'National Action Plan')], max_length=32),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='impacted_entity',
            field=models.CharField(max_length=8192),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='req_deadline',
            field=models.CharField(max_length=512),
        ),
    ]
