# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0020_auto_20170307_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_status',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
