# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0026_policy_nonpublic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('abbr', models.CharField(blank=True, max_length=64)),
                ('omb_agency_code', models.CharField(blank=True, max_length=8)),
                ('nonpublic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='agency',
            name='groups',
            field=models.ManyToManyField(to='reqs.AgencyGroup'),
        ),
    ]
