# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0030_auto_20170517_2035'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE INDEX reqs_requirement_gin_search
                ON reqs_requirement
                USING GIN (to_tsvector('english', req_text))
            """,
            "DROP INDEX reqs_requirement_gin_search"
        ),
    ]
