# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0031_auto_20170601_1631'),
    ]

    operations = [
        migrations.RunSQL(
            """
                UPDATE reqs_policy
                SET issuing_body = (
                    --- While each policy *should* have at least one
                    --- requirement and all requirements for a given policy
                    --- *should* have the same issuing body, we'll play it
                    --- safe and use MAX to grab lexicographically last value
                    --- and COALESCE to give a default when no requirements
                    --- are present.
                    SELECT COALESCE(MAX(r.issuing_body), '')
                    FROM reqs_requirement r
                    WHERE r.policy_id = reqs_policy.id
                )
            """, """
                UPDATE reqs_requirement
                SET issuing_body = (
                    SELECT p.issuing_body
                    FROM reqs_policy p
                    WHERE reqs_requirement.policy_id = p.id
                )
            """)
    ]
