# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0034_merge_20170605_1637'),
        ('reqs', '0032_auto_20170519_1952'),
    ]

    operations = [
    ]
