# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reqs', '0004_remove_policy_managing_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=1024)),
                ('node_type', models.CharField(max_length=64)),
                ('type_emblem', models.CharField(max_length=16)),
                ('text', models.TextField(blank=True)),
                ('left', models.PositiveIntegerField()),
                ('right', models.PositiveIntegerField()),
                ('depth', models.PositiveIntegerField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reqs.Policy')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='docnode',
            unique_together=set([('policy', 'identifier')]),
        ),
        migrations.AlterIndexTogether(
            name='docnode',
            index_together=set([('policy', 'identifier')]),
        ),
    ]
