# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootnoteCitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('doc_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footnotecitations', to='document.DocNode')),
                ('footnote_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='document.DocNode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
