# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_footnotecitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='docnode',
            name='marker',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
