# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0008_no_blank_slugs_allowed'),
        ('document', '0004_externallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='InlineRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('doc_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inlinerequirements', to='document.DocNode')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reqs.Requirement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
