# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_inlinerequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('doc_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cites', to='document.DocNode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
