# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_inlinerequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='docnode',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
