# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_docnode_title'),
        ('document', '0006_cite'),
    ]

    operations = [
    ]
