# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 11:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_merge_20171207_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docnode',
            name='type_emblem',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('[A-Za-z0-9]+', message='Only alphanumeric characters are allowed.')]),
        ),
    ]
